config/routes.rb
CMS::Application.routes.draw do

  devise_for :users

  resources :key_terms

  resources :critical_processes do
    member do
      post :key_term_add
      post :key_term_remove
    end
  end

  match "/dynamic_create" => "key_terms#dynamic_create", :as => :dynamic_create

  root :to => "critical_processes#index"

end

app/models/critical_process.rb
class CriticalProcess < ActiveRecord::Base
  has_many :categories, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  has_many :roles, :dependent => :destroy, :primary_key => :cp_secondary_id
  has_and_belongs_to_many :key_terms
  accepts_nested_attributes_for :categories, :reject_if => lambda { |a| a[:category_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :lessons, :reject_if => lambda { |a| a[:lesson_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :key_terms, :reject_if => lambda {|a| a[:term].blank? }

  after_create :new_cp
  # method which is called everything a new critical process is created to create the 2 new roles for that new CP
  def create_roles
    Role.create :name => "#{self.cp_title} edit", :critical_process_id => self.id, :edit => true, :review => false
    Role.create :name => "#{self.cp_title} review", :critical_process_id => self.id, :edit => false, :review => true
  end

  def set_secondary_id
      self.update_attribute :cp_secondary_id, self.id
  end

  def new_cp
    if self.cp_secondary_id.blank?
      set_secondary_id
      create_roles
    end
  end

  # method to retrieve all key terms that are no assigned to a CP
  def unassigned_key_terms
    KeyTerm.find(:all) - self.key_terms
  end

  # method to check if a key term already belongs to a critical process.
  def has_key_term(key_term)
    self.key_terms.include?(key_term)
  end

  def editors
    list_of_users = Array.new
    for role in self.roles
      if role.edit
         list_of_users << role.users
      end
    end
    return list_of_users
  end

end

app/controllers/critical_processes_controller.rb
class CriticalProcessesController < ApplicationController

  before_filter :authenticate_user!
  authorize_resource


  # GET /critical_processes
  # GET /critical_processes.xml
  def index
    @critical_processes = CriticalProcess.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @critical_processes }
    end
  end

  # GET /critical_processes/1
  # GET /critical_processes/1.xml
  def show
    @critical_process = CriticalProcess.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @critical_process }
    end
  end

  # GET /critical_processes/new
  # GET /critical_processes/new.xml
  def new
    @critical_process = CriticalProcess.new
    2.times do
       category = @critical_process.categories.build
       2.times { category.capability_building_blocks.build }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @critical_process }
    end
  end

  # GET /critical_processes/1/edit
  def edit
    @critical_process = CriticalProcess.find(params[:id])
  end

  # POST /critical_processes
  # POST /critical_processes.xml
  def create
    @critical_process = CriticalProcess.new(params[:critical_process])

    respond_to do |format|
      if @critical_process.save
        format.html { redirect_to(@critical_process, :notice => 'Critical process was successfully created.') }
        format.xml  { render :xml => @critical_process, :status => :created, :location => @critical_process }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @critical_process.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /critical_processes/1
  # PUT /critical_processes/1.xml
  def update
    #here we make sure that if all key term checkbox's' are unpicked then set the key_term_ids array to empty
    params[:critical_process][:key_term_ids] ||= []
    @critical_process = CriticalProcess.find(params[:id])
    if params[:critical_process]["cp_secondary_id"].blank?
        @critical_process.update_attributes(params[:critical_process])
        redirect_to(@critical_process, :notice => 'Critical process was successfully updated.')
    else
      revision = CriticalProcess.create(params[:critical_process])
      revision.update_attribute :cp_secondary_id, params[:critical_process]['cp_secondary_id']
      redirect_to(revision, :notice => 'Revision was successfully updated.')
    end
  end


  # DELETE /critical_processes/1
  # DELETE /critical_processes/1.xml
  def destroy
    @critical_process = CriticalProcess.find(params[:id])
    @critical_process.destroy

    respond_to do |format|
      format.html { redirect_to(critical_processes_url) }
      format.xml  { head :ok }
    end
  end

  #method to add a key term to a CP, this will be accessible through ajax (JavaScript)
  def key_term_add
    @critical_process = CriticalProcess.find(params[:id])
    @key_term = KeyTerm.find(params[:key_term])

    unless @critical_process.has_key_term(@key_term)
      @critical_process.key_terms << @key_term
      flash[:notice] = 'Key Term added successfully'
    else
      flash[:error] = 'Key term was already assigned'
    end
  end

  #method for removing key terms from a CP
  def key_term_remove
    @critical_process = CriticalProcess.find(params[:id])
    key_terms_ids = params[:key_terms]

    unless key_terms_ids.blank?
      key_terms_ids.each do | key_term_id|
        key_term = KeyTerm.find(key_term_id)
        if @critical_process.has_key_term(key_term)
          logger.info "removing key term #{key_term.id} from critical proccess"
          @critical_process.key_terms.delete(key_term)
          flash[:notice] = "Key term has been removed"
        end
      end
    end
  end
end

app/helpers/critical_processes_helper.rb
module CriticalProcessesHelper
end

app/views/critical_processes/_capability_building_block_fields.html.erb
<p class="fields">
  <%= f.label :cbb_title, "CBB Title" %><br/>
  <%= f.text_area :cbb_title, :rows => 2 %>
  <%= f.label :cbb_definition, "CBB Description" %><br/>
  <%= f.text_area :cbb_definition, :rows => 4 %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/critical_processes/_category_fields.html.erb
<div class="fields">
<p>
  <%= f.label :category_title, "Category Title" %>
  <%= link_to_remove_fields "remove", f %><br/>
  <%= f.text_area :category_title, :rows => 2 %>

</p>
<% f.fields_for :capability_building_blocks do |builder| %>
    <%= render 'capability_building_block_fields', :f => builder %>
<% end %>
  <p><%= link_to_add_fields "Add CBB", f, :capability_building_blocks %></p>
</div>

app/views/critical_processes/_form.html.erb
<%= form_for(@critical_process) do |f| %>
  <% if @critical_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@critical_process.errors.count, "error") %> prohibited this critical_process from being saved:</h2>

      <ul>
      <% @critical_process.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :cp_secondary_id %>
  </div>
  <div class="field">
    <%= f.label :cp_title %><br />
    <%= f.text_field :cp_title %>
  </div>
  <div class="field">
    <%= f.label :cp_intro %><br />
    <%= f.text_area :cp_intro %>
  </div>
  <div class="field">
    <%= f.label :cp_definition %><br />
    <%= f.text_area :cp_definition %>
  </div>
  <div class="field">
    <%= f.label :in_scope %><br />
    <%= f.text_area :in_scope %>
  </div>
  <div class="field">
    <%= f.label :out_scope %><br />
    <%= f.text_area :out_scope %>
  </div>
  <div class="categories">
    <% f.fields_for :categories do |builder| %>
        <%= render 'category_fields', :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Category", f, :categories %></p>
  </div>
  <div class="lessons">
    <% f.fields_for :lessons do |builder| %>
       <%= render 'lesson_fields', :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Lesson", f, :lessons %></p>
  </div>

  <div id="key_terms_selection">

    <% for key_term in KeyTerm.find(:all) %>
       <%= check_box_tag "critical_process[key_term_ids][]", key_term.id, @critical_process.key_terms.include?(key_term) %>
       <%= key_term.term %>
    <% end %>

  </div>

  <a id="term_link" href='#'> Add Key Term </a>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

    <div id="new_key_term_dialog">
      <% @key_term = KeyTerm.new %>
     <%= form_for(@key_term, :remote => true ) do |f| %>


          <div class="field">
            <%= f.label :term %><br />
            <%= f.text_field :term %>
          </div>
          <div class="field">
            <%= f.label :meaning %><br />
            <%= f.text_area :meaning %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>


</div>

app/views/critical_processes/_lesson_fields.html.erb
<p class="fields">
  <%= f.label :lesson_title, "Lesson Title" %><br/>
  <%= f.text_area :lesson_title, :rows => 2 %>
  <%= f.label :lesson_definition, "Lesson Description" %><br/>
  <%= f.text_area :lesson_definition, :rows => 4 %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/critical_processes/edit.html.erb
<h1>Editing critical_process</h1>

<%= render 'form' %>

<%= link_to 'Show', @critical_process %> |
<%= link_to 'Back', critical_processes_path %>

app/views/critical_processes/index.html.erb
<h1>Listing critical_processes</h1>

<table>
  <tr>
    <th>Cp secondary</th>
    <th>Cp title</th>
    <th>Cp intro</th>
    <th>Cp definition</th>
    <th>In scope</th>
    <th>Out scope</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @critical_processes.each do |critical_process| %>
  <tr>
    <td><%= critical_process.cp_secondary_id %></td>
    <td><%= critical_process.cp_title %></td>
    <td><%= critical_process.cp_intro %></td>
    <td><%= critical_process.cp_definition %></td>
    <td><%= critical_process.in_scope %></td>
    <td><%= critical_process.out_scope %></td>
    <td><%= link_to 'Show', critical_process %></td>
    <td><%= link_to 'Edit', edit_critical_process_path(critical_process) %></td>
    <td><%= link_to 'Destroy', critical_process, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Critical process', new_critical_process_path %>

app/views/critical_processes/new.html.erb
<h1>New critical_process</h1>

<%= render 'form' %>

<%= link_to 'Back', critical_processes_path %>

app/views/critical_processes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Cp secondary:</b>
  <%= @critical_process.cp_secondary_id %>
</p>

<p>
  <b>Cp title:</b>
  <%= @critical_process.cp_title %>
</p>

<p>
  <b>Cp intro:</b>
  <%= @critical_process.cp_intro %>
</p>

<p>
  <b>Cp definition:</b>
  <%= @critical_process.cp_definition %>
</p>

<p>
  <b>In scope:</b>
  <%= @critical_process.in_scope %>
</p>

<p>
  <b>Out scope:</b>
  <%= @critical_process.out_scope %>
</p>

<ol>
  <% for category in @critical_process.categories %>
    <li>
      <%=h category.category_title %>
      <ul>
        <% for cbb in category.capability_building_blocks %>
            <li> <%=h cbb.cbb_title %></li>
            <li> <%=h cbb.cbb_definition %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>
<b>Lessons Learned:</b>
<ol>
  <% for lesson in @critical_process.lessons %>
    <li>
      <%=h lesson.lesson_title %>
      <%=h lesson.lesson_definition %>
    </li>
  <% end %>
</ol>

<p>
  <b>Key term's</b>
  <% if @critical_process.key_terms.count > 0 %>
     <%= @critical_process.key_terms.collect {|key_term| link_to(key_term.term, key_term)}.join(", ") %>
  <% else %>
     This process has no Key terms
  <% end %>
</p>

<%= link_to 'Edit', edit_critical_process_path(@critical_process) %> |
<%= link_to 'Back', critical_processes_path %>