config/routes.rb
CMS::Application.routes.draw do

  devise_for :users

  resources :key_terms

  resources :critical_processes do
    member do
      post :key_term_add
      post :key_term_remove
    end
  end

  match "/dynamic_create" => "key_terms#dynamic_create", :as => :dynamic_create

  root :to => "critical_processes#index"

end

app/models/critical_process.rb
class CriticalProcess < ActiveRecord::Base
  has_many :categories, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  has_many :roles, :dependent => :destroy, :primary_key => :cp_secondary_id
  has_and_belongs_to_many :key_terms
  accepts_nested_attributes_for :categories, :reject_if => lambda { |a| a[:category_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :lessons, :reject_if => lambda { |a| a[:lesson_title].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :key_terms, :reject_if => lambda {|a| a[:term].blank? }

  after_create :new_cp
  # method which is called everything a new critical process is created to create the 2 new roles for that new CP
  def create_roles
    Role.create :name => "#{self.cp_title} edit", :critical_process_id => self.id, :edit => true, :review => false
    Role.create :name => "#{self.cp_title} review", :critical_process_id => self.id, :edit => false, :review => true
  end

  def set_secondary_id
      self.update_attribute :cp_secondary_id, self.id
  end

  def new_cp
    if self.cp_secondary_id.blank?
      set_secondary_id
      create_roles
    end
  end

  # method to retrieve all key terms that are no assigned to a CP
  def unassigned_key_terms
    KeyTerm.find(:all) - self.key_terms
  end

  # method to check if a key term already belongs to a critical process.
  def has_key_term(key_term)
    self.key_terms.include?(key_term)
  end

  def editors
    list_of_users = Array.new
    for role in self.roles
      if role.edit
         list_of_users << role.users
      end
    end
    return list_of_users
  end

end

app/models/key_term.rb
class KeyTerm < ActiveRecord::Base
  has_and_belongs_to_many :critical_processes
end

app/controllers/key_terms_controller.rb
class KeyTermsController < ApplicationController
  # GET /key_terms
  # GET /key_terms.xml
  def index
    @key_terms = KeyTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @key_terms }
    end
  end

  # GET /key_terms/1
  # GET /key_terms/1.xml
  def show
    @key_term = KeyTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @key_term }
    end
  end

  # GET /key_terms/new
  # GET /key_terms/new.xml
  def new
    @key_term = KeyTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @key_term }
    end
  end

  # GET /key_terms/1/edit
  def edit
    @key_term = KeyTerm.find(params[:id])
  end

  # POST /key_terms
  # POST /key_terms.xml
  def create
    @key_term = KeyTerm.new(params[:key_term])

    respond_to do |format|
      if @key_term.save
        format.html { redirect_to(@key_term, :notice => 'Key term was successfully created.') }
        format.xml  { render :xml => @key_term, :status => :created, :location => @key_term }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @key_term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /key_terms/1
  # PUT /key_terms/1.xml
  def update
    @key_term = KeyTerm.find(params[:id])

    respond_to do |format|
      if @key_term.update_attributes(params[:key_term])
        format.html { redirect_to(@key_term, :notice => 'Key term was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @key_term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /key_terms/1
  # DELETE /key_terms/1.xml
  def destroy
    @key_term = KeyTerm.find(params[:id])
    @key_term.destroy

    respond_to do |format|
      format.html { redirect_to(key_terms_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/key_terms_helper.rb
module KeyTermsHelper
end

app/views/key_terms/_form.html.erb
<%= form_for(@key_term ) do |f| %>
  <% if @key_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_term.errors.count, "error") %> prohibited this key_term from being saved:</h2>

      <ul>
      <% @key_term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %><br />
    <%= f.text_field :term %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br />
    <%= f.text_area :meaning %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/key_terms/create.js.erb
$("#new_key_term_dialog").dialog("close");
$("#key_terms_selection").append("<%= escape_javascript(check_box_tag 'critical_process[key_term_ids][]', "#{@key_term.id.to_i}", true, :id => 'critical_process_key_term_ids_' ) %>");
$("#key_terms_selection").append("<%= escape_javascript(@key_term.term )%>");
$('#key_term_term').val("");
$('#key_term_meaning').val("");

app/views/key_terms/edit.html.erb
<h1>Editing key_term</h1>
<%= render 'form' %>

<%= link_to 'Show', @key_term %> |
<%= link_to 'Back', key_terms_path %>

app/views/key_terms/index.html.erb
<h1>Listing key_terms</h1>

<table>
  <tr>
    <th>Term</th>
    <th>Meaning</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @key_terms.each do |key_term| %>
  <tr>
    <td><%= key_term.term %></td>
    <td><%= key_term.meaning %></td>
    <td><%= link_to 'Show', key_term %></td>
    <td><%= link_to 'Edit', edit_key_term_path(key_term) %></td>
    <td><%= link_to 'Destroy', key_term, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Key term', new_key_term_path %>

app/views/key_terms/new.html.erb
<h1>New key_term</h1>
    <%= render 'form' %>
    <%= link_to 'Back', key_terms_path %>

app/views/key_terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Term:</b>
  <%= @key_term.term %>
</p>

<p>
  <b>Meaning:</b>
  <%= @key_term.meaning %>
</p>


<%= link_to 'Edit', edit_key_term_path(@key_term) %> |
<%= link_to 'Back', key_terms_path %>